-- CREATE USER USER_0D_1 IF IT DOESN'T ALREADY EXIST
-- GIVE ALL PERMISSIONS
CREATE USER IF NOT EXISTS 'user_0d_1'@'localhost' IDENTIFIED BY 'user_0d_1_pwd';
GRANT ALL PRIVILEGES ON *.* TO 'user_0d_1'@'localhost';
