-- CREATES THE DATABASE hbtn_0d_2 AND THE USER user_0d_2
-- GRANT SELECT TO USER IN hbtn_0d_2 DATABASE
CREATE DATABASE IF NOT EXISTS hbtn_0d_2;
CREATE USER IF NOT EXISTS 'user_0d_2'@'localhost' IDENTIFIED BY 'user_0d_2_pwd';
GRANT SELECT ON hbtn_0d_2.* TO user_0d_2@localhost;
